stages:
  - test_e2e
  - test_components
  - deploy

variables:
  # Se fuerza a clonar el repositorio para tener el historial completo
  GIT_STRATEGY: clone

test_e2e:
  stage: test_e2e
  image: cypress/browsers:node-22.12.0-chrome-131.0.6778.108-1-ff-133.0-edge-131.0.2903.70-1
  script:
    - npm install --legacy-peer-deps
    - npm run cy:run
    - sed -i 's/<?xml version="1.1"/<?xml version="1.0"/' cypress/results/junit/test-results.xml
  artifacts:
    when: always
    paths:
      - cypress/results/junit/test-results.xml
      - cypress/screenshots
      - cypress/videos
    reports:
      junit:
        - cypress/results/junit/test-results.xml
  only:
    - merge_requests
    - main

test_components:
  stage: test_components
  image: cypress/browsers:node-22.12.0-chrome-131.0.6778.108-1-ff-133.0-edge-131.0.2903.70-1
  script:
    - npm install --legacy-peer-deps
    - npm run cy:run:component
    - sed -i 's/<?xml version="1.1"/<?xml version="1.0"/' cypress/results/junit/test-results.xml
  artifacts:
    when: always
    paths:
      - cypress/results/junit/test-results.xml
    reports:
      junit:
        - cypress/results/junit/test-results.xml
  only:
    - main

deploy:
  stage: deploy
  image: node:16
  script:
    - git config --global user.email "miguel.a.rodriguez.r@gmail.com"
    - git config --global user.name "Mig Rod"
    - git remote add github "https://$GITHUB_TOKEN@github.com/MiguelRodriguezR/Masseru_pos_frontend.git"
    - git push github HEAD:main --force
  only:
    - main
  when: manual
  dependencies:
    - test_components
    - test_e2e
